#!/bin/sh -eux

ub_install
mkdir -p "${UB_INSTALLDIR}"/usr/share/abe/images
  cp -r images/ maps/ sounds/ "${UB_INSTALLDIR}"/usr/share/abe/
  cd "${UB_INSTALLDIR}"/usr/share/abe/images
  tar -xf "${UB_COMPILEDIR}"/images/images.tar abe.bmp
